openapi: 3.0.0
info:
  title: Common Fate Provider Registry
  version: "1.0"
  contact:
    name: Common Fate
    url: "https://api.registry.commonfate.io"
  description: The Common Fate Provider Registry API.
servers:
  - url: "http://localhost:9001"
paths:
  "/v1alpha1/providers/{publisher}/{name}/{version}":
    parameters:
      - schema:
          type: string
        name: publisher
        in: path
        required: true
      - schema:
          type: string
        name: version
        in: path
        required: true
      - schema:
          type: string
        name: name
        in: path
        required: true
    get:
      summary: Get Provider
      operationId: get-provider
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProviderDetail"
        "404":
          $ref: "#/components/responses/ErrorResponse"
        "500":
          $ref: "#/components/responses/ErrorResponse"
      tags:
        - Public
  "/v1alpha1/providers/{publisher}/{name}/{version}/setup":
    parameters:
      - schema:
          type: string
        name: publisher
        in: path
        required: true
      - schema:
          type: string
        name: version
        in: path
        required: true
      - schema:
          type: string
        name: name
        in: path
        required: true
    get:
      summary: Get Provider Setup Docs
      operationId: get-provider-setup-docs
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
      tags:
        - Public
  "/v1alpha1/providers/{publisher}/{name}/{version}/usage":
    parameters:
      - schema:
          type: string
        name: publisher
        in: path
        required: true
      - schema:
          type: string
        name: version
        in: path
        required: true
      - schema:
          type: string
        name: name
        in: path
        required: true
    get:
      summary: Get Provider Usage Doc
      operationId: get-provider-usage-doc
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
      tags:
        - Public
      description: ""
  /v1alpha1/providers:
    get:
      summary: List Providers
      tags:
        - Public
      responses:
        "200":
          $ref: "#/components/responses/ListProvidersResponse"
        "500":
          $ref: "#/components/responses/ErrorResponse"
      operationId: list-all-providers
      parameters:
        - schema:
            type: boolean
          in: query
          name: withDev
          description: withDev flag will return all providers including dev providers
  /v1alpha1/signup/oauth2/github:
    parameters: []
    get:
      summary: ""
      operationId: get-v1alpha1-signup-oauth2-github
      responses:
        "201":
          description: ""
          content:
            application/json:
              schema:
                type: object
                properties:
                  User:
                    $ref: "#/components/schemas/UserDetail"
        "":
          description: ""
      description: "Sign Up to CommonFate using Github Oauth2 "
  /v1alpha1/signup/oauth2/callback:
    parameters: []
    get:
      summary: ""
      operationId: get-v1alpha1-signup-oauth2-callback
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: object
                properties:
                  User:
                    $ref: "#/components/schemas/UserDetail"
        "":
          description: ""
      description: Github oauth2 callback URL
      parameters:
        - schema:
            type: string
          in: query
          name: code
  /v1alpha1/register:
    parameters: []
    post:
      summary: ""
      operationId: post-v1alpha1-register
      responses:
        "201":
          description: Created
      description: Register User to Common Fate Provider Registry
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                username:
                  type: string
  /v1alpha1/health:
    get:
      summary: Healthcheck
      tags: []
      responses:
        "200":
          description: OK
      operationId: healthcheck
      description: Returns a HTTP 200 OK response if the registry service is healthy.
components:
  schemas:
    ProviderDetail:
      title: ProviderDetail
      x-stoplight:
        id: ad9be36dbe096
      type: object
      description: A registered provider version
      properties:
        publisher:
          type: string
        name:
          type: string
        version:
          type: string
        lambdaAssetS3Arn:
          type: string
        cfnTemplateS3Arn:
          type: string
        icon:
          type: string
        schema:
          $ref: "#/components/schemas/Schema"
      required:
        - publisher
        - name
        - version
        - lambdaAssetS3Arn
        - cfnTemplateS3Arn
        - schema
    Provider:
      title: Provider
      type: object
      description: A registered provider version
      x-stoplight:
        id: b4d9111a1ff26
      properties:
        publisher:
          type: string
        name:
          type: string
        version:
          type: string
      required:
        - publisher
        - name
        - version
    DiagnosticLog:
      title: DiagnosticLog
      x-stoplight:
        id: xq5uhsxpiml1y
      type: object
      properties:
        level:
          $ref: "#/components/schemas/LogLevel"
        msg:
          type: string
      required:
        - level
        - msg
    DescribeResponse:
      title: DescribeResponse
      x-stoplight:
        id: atffan2bx099r
      type: object
      properties:
        provider:
          $ref: "#/components/schemas/Provider"
        config:
          type: object
        healthy:
          type: boolean
        diagnostics:
          type: array
          items:
            $ref: "#/components/schemas/DiagnosticLog"
        schema:
          $ref: "#/components/schemas/Schema"
      required:
        - provider
        - config
        - healthy
        - diagnostics
        - schema
    LogLevel:
      title: LogLevel
      x-stoplight:
        id: r9cextojd3t67
      type: string
      enum:
        - INFO
        - ERROR
        - WARNING
    Config:
      properties:
        description:
          description: The usage for the config variable.
          title: Description
          type: string
        secret:
          default: false
          title: Secret
          type: boolean
        type:
          enum:
            - string
          title: Type
          type: string
      required:
        - type
      title: Config
      type: object
    Loader:
      description: |-
        A callable function in the provider which can
        load resources.

        Additional fields for loader configuration may be added
        in a future specification.
      properties:
        title:
          title: Title
          type: string
      required:
        - title
      title: Loader
      type: object
    Meta:
      properties:
        framework:
          description: The Provider Developer Kit framework version which published the schema.
          title: Framework
          type: string
      title: Meta
      type: object
    Providers:
      properties:
        name:
          title: Name
          type: string
        publisher:
          title: Publisher
          type: string
        version:
          title: Version
          type: string
      required:
        - publisher
        - name
        - version
      title: Provider
      type: object
    Resources:
      properties:
        loaders:
          additionalProperties:
            $ref: "#/components/schemas/Loader"
          x-go-type: "map[string]Loader"
          title: Loaders
          type: object
        types:
          description: the types of resources
          title: Types
          type: object
      required:
        - loaders
        - types
      title: Resources
      type: object
    Target:
      properties:
        properties:
          additionalProperties:
            $ref: "#/components/schemas/TargetField"
          x-go-type: "map[string]TargetField"
          description: the actual properties of the target.
          title: Properties
          type: object
        type:
          description: included for compatibility with JSON Schema - all targets are currently objects.
          enum:
            - object
          title: Type
          type: string
      required:
        - type
        - properties
      title: Target
      type: object
    TargetField:
      properties:
        description:
          title: Description
          type: string
        resource:
          description: "If specified, the type of the resource the field should be populated from."
          title: Resource
          type: string
        title:
          title: Title
          type: string
        type:
          enum:
            - string
          title: Type
          type: string
      required:
        - type
      title: TargetField
      type: object
    Schema:
      description: The schema for a Common Fate Provider.
      properties:
        $id:
          type: string
        $schema:
          type: string
        config:
          additionalProperties:
            $ref: "#/components/schemas/Config"
          x-go-type: "map[string]Config"
          title: Config
          type: object
        meta:
          $ref: "#/components/schemas/Meta"
        provider:
          $ref: "#/components/schemas/Provider"
        resources:
          $ref: "#/components/schemas/Resources"
        targets:
          additionalProperties:
            $ref: "#/components/schemas/Target"
          x-go-type: "map[string]Target"
          title: Targets
          type: object
      required:
        - meta
        - $id
        - $schema
      title: Schema
      type: object
    UserDetail:
      description: User Details returned by Github Authenticator
      title: UserDetail
      type: object
      x-stoplight:
        id: 3af5c75a5731d
      properties:
        login:
          type: string
        name:
          type: string
        company:
          type: string
        email:
          type: string
        id:
          type: number
  requestBodies: {}
  responses:
    HealthResponse:
      description: Healthcheck response body.
      content:
        application/json:
          schema:
            type: object
            properties:
              healthy:
                type: boolean
            required:
              - healthy
          examples: {}
    ErrorResponse:
      description: An error returned from the API.
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
            required:
              - error
          examples: {}
    ListProvidersResponse:
      description: Example response
      content:
        application/json:
          schema:
            type: object
            properties:
              providers:
                type: array
                items:
                  $ref: "#/components/schemas/ProviderDetail"
              next:
                type: string
                nullable: true
            required:
              - providers
              - next
tags:
  - name: Public
  - name: Team
