openapi: 3.0.0
info:
  title: Example API
  version: '1.0'
  contact:
    name: Common Fate
    url: 'https://commonfate.io'
  description: Example API
servers:
  - url: 'http://localhost:9001'
paths:
  '/api/v1/team/{team}/providers/{name}/{version}':
    parameters:
      - schema:
          type: string
        name: team
        in: path
        required: true
      - schema:
          type: string
        name: version
        in: path
        required: true
      - schema:
          type: string
        name: name
        in: path
        required: true
    get:
      summary: Get Provider
      operationId: get-provider
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProviderDetail'
      tags:
        - Public
  '/api/v1/team/{team}/providers/{name}/{version}/setup':
    parameters:
      - schema:
          type: string
        name: team
        in: path
        required: true
      - schema:
          type: string
        name: version
        in: path
        required: true
      - schema:
          type: string
        name: name
        in: path
        required: true
    get:
      summary: Get Provider Setup Docs
      operationId: get-provider-setup-docs
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
      tags:
        - Public
  '/api/v1/team/{team}/providers/{name}/{version}/usage':
    parameters:
      - schema:
          type: string
        name: team
        in: path
        required: true
      - schema:
          type: string
        name: version
        in: path
        required: true
      - schema:
          type: string
        name: name
        in: path
        required: true
    get:
      summary: Get Provider Usage Doc
      operationId: get-provider-usage-doc
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
      tags:
        - Public
      description: ''
  /api/v1/providers:
    get:
      summary: List Providers
      tags:
        - Public
      responses:
        '200':
          $ref: '#/components/responses/ListProvidersResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
      operationId: list-all-providers
  '/api/v1/admin/providersetups/{providersetupId}/instructions':
    get:
      summary: Get the setup instructions for an Access Provider
      tags:
        - Admin
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProviderSetupInstructions'
      operationId: admin-get-providersetup-instructions
      description: Get the setup instructions for an Access Provider.
    parameters:
      - schema:
          type: string
        name: providersetupId
        in: path
        required: true
components:
  schemas:
    ProviderDetail:
      title: ProviderDetail
      x-stoplight:
        id: ad9be36dbe096
      type: object
      description: A registered provider version
      properties:
        publisher:
          type: string
        name:
          type: string
        version:
          type: string
        lambdaAssetS3Arn:
          type: string
        cfnTemplateS3Arn:
          type: string
        schema:
          $ref: '#/components/schemas/ProviderSchema'
      required:
        - publisher
        - name
        - version
        - lambdaAssetS3Arn
        - cfnTemplateS3Arn
        - schema
    Provider:
      title: Provider
      type: object
      description: A registered provider version
      x-stoplight:
        id: b4d9111a1ff26
      properties:
        publisher:
          type: string
        name:
          type: string
        version:
          type: string
      required:
        - publisher
        - name
        - version
    ConfigArgument:
      title: ConfigArgument
      x-stoplight:
        id: b867e439e8b53
      type: object
      properties:
        type:
          type: string
          enum:
            - STRING
            - SECRETSTRING
        secret:
          type: boolean
        usage:
          type: string
      required:
        - type
        - secret
        - usage
    TargetArgument:
      title: TargetArgument
      x-stoplight:
        id: 1b080aa3276c2
      type: object
      description: 'Define the metadata, data type and UI elements for the argument'
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        resourceName:
          type: string
        ruleFormElement:
          type: string
          enum:
            - INPUT
            - MULTISELECT
            - SELECT
        requestFormElement:
          type: string
          enum:
            - SELECT
          description: 'Optional form element for the request form, if not provided, defaults to multiselect'
      required:
        - id
        - title
        - ruleFormElement
        - requestFormElement
        - groups
    ProviderSchema:
      title: ProviderSchema
      x-stoplight:
        id: d3gvj3cbsoe70
      type: object
      properties:
        config:
          $ref: '#/components/schemas/ConfigSchema'
        audit:
          $ref: '#/components/schemas/AuditSchema'
        target:
          $ref: '#/components/schemas/TargetSchema'
      required:
        - config
        - audit
        - target
    TargetMode:
      title: TargetMode
      x-stoplight:
        id: o2oindupo85hh
      type: object
      properties:
        schema:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/TargetArgument'
      required:
        - schema
    TargetSchema:
      title: TargetSchema
      x-stoplight:
        id: tk7obmea4shbx
      type: object
      additionalProperties:
        $ref: '#/components/schemas/TargetMode'
    ConfigSchema:
      title: ConfigSchema
      x-stoplight:
        id: a4b73cf497883
      type: object
      additionalProperties:
        $ref: '#/components/schemas/ConfigArgument'
    AuditSchema:
      title: AuditSchema
      x-stoplight:
        id: bacx4ke9fh1bo
      type: object
      properties:
        resourceLoaders:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/ResourceLoader'
        resources:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/Resource'
      required:
        - resourceLoaders
    ResourceLoader:
      title: ResourceLoader
      x-stoplight:
        id: j3ehgrwrocbeh
      type: object
      properties:
        title:
          type: string
      required:
        - title
    Resource:
      title: Resource
      type: object
      x-stoplight:
        id: b9183456d960d
      properties:
        type:
          type: string
        data:
          type: object
          required:
            - id
          properties:
            id:
              type: string
      required:
        - type
        - data
    DiagnosticLog:
      title: DiagnosticLog
      x-stoplight:
        id: xq5uhsxpiml1y
      type: object
      properties:
        level:
          type: string
          enum:
            - info
            - error
        msg:
          type: string
      required:
        - level
        - msg
    ConfigValidation:
      title: ConfigValidation
      x-stoplight:
        id: roz5uwo0i6jrw
      type: object
      properties:
        success:
          type: boolean
        logs:
          type: array
          items:
            $ref: '#/components/schemas/DiagnosticLog'
      required:
        - success
        - logs
    DescribeResponse:
      title: DescribeResponse
      x-stoplight:
        id: atffan2bx099r
      type: object
      properties:
        provider:
          $ref: '#/components/schemas/Provider'
        config:
          type: object
        configValidation:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/ConfigValidation'
        schema:
          $ref: '#/components/schemas/ProviderSchema'
      required:
        - provider
        - config
    ProviderSetupInstructions:
      title: ProviderSetupInstructions
      x-stoplight:
        id: w5avwzeow2bj9
      type: object
      properties:
        stepDetails:
          type: array
          items:
            $ref: '#/components/schemas/ProviderSetupStepDetails'
      required:
        - stepDetails
    ProviderSetupStepDetails:
      title: ProviderSetupStepDetails
      x-stoplight:
        id: w5avwzeow2bj9
      type: object
      properties:
        title:
          type: string
        instructions:
          type: string
        configFields:
          type: array
          items:
            $ref: '#/components/schemas/ConfigArgument'
      required:
        - title
        - instructions
        - configFields
  requestBodies: {}
  responses:
    HealthResponse:
      description: Healthcheck response body.
      content:
        application/json:
          schema:
            type: object
            properties:
              healthy:
                type: boolean
            required:
              - healthy
          examples: {}
    ErrorResponse:
      description: An error returned from the API.
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
            required:
              - error
          examples: {}
    ListProvidersResponse:
      description: Example response
      content:
        application/json:
          schema:
            type: object
            properties:
              providers:
                type: array
                items:
                  $ref: '#/components/schemas/ProviderDetail'
              next:
                type: string
                nullable: true
            required:
              - providers
              - next
tags:
  - name: Public
  - name: Team
