// Package providerregistrysdk provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package providerregistrysdk

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
)

// Defines values for ConfigType.
const (
	ConfigTypeString ConfigType = "string"
)

// Defines values for LogLevel.
const (
	ERROR   LogLevel = "ERROR"
	INFO    LogLevel = "INFO"
	WARNING LogLevel = "WARNING"
)

// Defines values for TargetType.
const (
	Object TargetType = "object"
)

// Defines values for TargetFieldType.
const (
	TargetFieldTypeString TargetFieldType = "string"
)

// Config defines model for Config.
type Config struct {
	// The usage for the config variable.
	Description *string    `json:"description,omitempty"`
	Secret      *bool      `json:"secret,omitempty"`
	Type        ConfigType `json:"type"`
}

// ConfigType defines model for Config.Type.
type ConfigType string

// DescribeResponse defines model for DescribeResponse.
type DescribeResponse struct {
	Config      map[string]interface{} `json:"config"`
	Diagnostics []DiagnosticLog        `json:"diagnostics"`
	Healthy     bool                   `json:"healthy"`

	// A registered provider version
	Provider Provider `json:"provider"`

	// The schema for a Common Fate Provider.
	Schema Schema `json:"schema"`
}

// DiagnosticLog defines model for DiagnosticLog.
type DiagnosticLog struct {
	Level LogLevel `json:"level"`
	Msg   string   `json:"msg"`
}

// A callable function in the provider which can
// load resources.
//
// Additional fields for loader configuration may be added
// in a future specification.
type Loader struct {
	Title string `json:"title"`
}

// LogLevel defines model for LogLevel.
type LogLevel string

// Meta defines model for Meta.
type Meta struct {
	// The Provider Developer Kit framework version which published the schema.
	Framework *string `json:"framework,omitempty"`
}

// A registered provider version
type Provider struct {
	Name      string `json:"name"`
	Publisher string `json:"publisher"`
	Version   string `json:"version"`
}

// A registered provider version
type ProviderDetail struct {
	CfnTemplateS3Arn string `json:"cfnTemplateS3Arn"`
	CreatedAt        string `json:"createdAt"`
	LambdaAssetS3Arn string `json:"lambdaAssetS3Arn"`

	// Metadata from provider.toml file for a Provider
	Meta      *ProviderMetaInfo `json:"meta,omitempty"`
	Name      string            `json:"name"`
	Publisher string            `json:"publisher"`

	// The schema for a Common Fate Provider.
	Schema    Schema `json:"schema"`
	UpdatedAt string `json:"updatedAt"`
	Version   string `json:"version"`
}

// Metadata from provider.toml file for a Provider
type ProviderMetaInfo struct {
	DisplayName *string `json:"displayName,omitempty"`
	Icon        *string `json:"icon,omitempty"`
	Source      *string `json:"source,omitempty"`
}

// Providers defines model for Providers.
type Providers struct {
	Name      string `json:"name"`
	Publisher string `json:"publisher"`
	Version   string `json:"version"`
}

// Resources defines model for Resources.
type Resources struct {
	Loaders map[string]Loader `json:"loaders"`

	// the types of resources
	Types map[string]interface{} `json:"types"`
}

// The schema for a Common Fate Provider.
type Schema struct {
	Id     string             `json:"$id"`
	Schema string             `json:"$schema"`
	Config *map[string]Config `json:"config,omitempty"`
	Meta   Meta               `json:"meta"`

	// A registered provider version
	Provider  *Provider          `json:"provider,omitempty"`
	Resources *Resources         `json:"resources,omitempty"`
	Targets   *map[string]Target `json:"targets,omitempty"`
}

// Target defines model for Target.
type Target struct {
	// the actual properties of the target.
	Properties map[string]TargetField `json:"properties"`

	// included for compatibility with JSON Schema - all targets are currently objects.
	Type TargetType `json:"type"`
}

// included for compatibility with JSON Schema - all targets are currently objects.
type TargetType string

// TargetField defines model for TargetField.
type TargetField struct {
	Description *string `json:"description,omitempty"`

	// If specified, the type of the resource the field should be populated from.
	Resource *string         `json:"resource,omitempty"`
	Title    *string         `json:"title,omitempty"`
	Type     TargetFieldType `json:"type"`
}

// TargetFieldType defines model for TargetField.Type.
type TargetFieldType string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Healthy bool `json:"healthy"`
}

// ListProvidersResponse defines model for ListProvidersResponse.
type ListProvidersResponse struct {
	Next      *string          `json:"next"`
	Providers []ProviderDetail `json:"providers"`
}

// ProviderReadmeResponse defines model for ProviderReadmeResponse.
type ProviderReadmeResponse struct {
	Readme string `json:"readme"`
}

// PublishProviderResponse defines model for PublishProviderResponse.
type PublishProviderResponse struct {
	CloudformationTemplateUploadUrl string `json:"cloudformationTemplateUploadUrl"`
	LambdaHandlerUploadUrl          string `json:"lambdaHandlerUploadUrl"`
	ReadmeUploadUrl                 string `json:"readmeUploadUrl"`

	// filename is the key and value is the upload URL
	RoleTemplateUploadURLs map[string]string `json:"roleTemplateUploadURLs"`
}

// PublishProviderRequest defines model for PublishProviderRequest.
type PublishProviderRequest struct {
	Dev       *bool  `json:"dev,omitempty"`
	Name      string `json:"name"`
	Publisher string `json:"publisher"`

	// an array of filenames for role templates to be uploaded
	RoleFiles []string `json:"roleFiles"`
	Version   string   `json:"version"`
}

// ListAllProvidersParams defines parameters for ListAllProviders.
type ListAllProvidersParams struct {
	// withDev flag will return all providers including dev providers
	WithDev *bool `form:"withDev,omitempty" json:"withDev,omitempty"`
}

// UserCompletePublishProviderJSONBody defines parameters for UserCompletePublishProvider.
type UserCompletePublishProviderJSONBody = Provider

// UserPublishProviderJSONRequestBody defines body for UserPublishProvider for application/json ContentType.
type UserPublishProviderJSONRequestBody PublishProviderRequest

// UserCompletePublishProviderJSONRequestBody defines body for UserCompletePublishProvider for application/json ContentType.
type UserCompletePublishProviderJSONRequestBody = UserCompletePublishProviderJSONBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// Healthcheck request
	Healthcheck(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListAllProviders request
	ListAllProviders(ctx context.Context, params *ListAllProvidersParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetProviderVersions request
	GetProviderVersions(ctx context.Context, publisher string, name string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetProvider request
	GetProvider(ctx context.Context, publisher string, name string, version string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetProviderReadme request
	GetProviderReadme(ctx context.Context, publisher string, name string, version string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UserPublishProvider request with any body
	UserPublishProviderWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	UserPublishProvider(ctx context.Context, body UserPublishProviderJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UserCompletePublishProvider request with any body
	UserCompletePublishProviderWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	UserCompletePublishProvider(ctx context.Context, body UserCompletePublishProviderJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) Healthcheck(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewHealthcheckRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListAllProviders(ctx context.Context, params *ListAllProvidersParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListAllProvidersRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetProviderVersions(ctx context.Context, publisher string, name string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetProviderVersionsRequest(c.Server, publisher, name)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetProvider(ctx context.Context, publisher string, name string, version string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetProviderRequest(c.Server, publisher, name, version)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetProviderReadme(ctx context.Context, publisher string, name string, version string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetProviderReadmeRequest(c.Server, publisher, name, version)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UserPublishProviderWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUserPublishProviderRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UserPublishProvider(ctx context.Context, body UserPublishProviderJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUserPublishProviderRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UserCompletePublishProviderWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUserCompletePublishProviderRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UserCompletePublishProvider(ctx context.Context, body UserCompletePublishProviderJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUserCompletePublishProviderRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewHealthcheckRequest generates requests for Healthcheck
func NewHealthcheckRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1alpha1/health")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListAllProvidersRequest generates requests for ListAllProviders
func NewListAllProvidersRequest(server string, params *ListAllProvidersParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1alpha1/providers")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	queryValues := queryURL.Query()

	if params.WithDev != nil {

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "withDev", runtime.ParamLocationQuery, *params.WithDev); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

	}

	queryURL.RawQuery = queryValues.Encode()

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetProviderVersionsRequest generates requests for GetProviderVersions
func NewGetProviderVersionsRequest(server string, publisher string, name string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "publisher", runtime.ParamLocationPath, publisher)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "name", runtime.ParamLocationPath, name)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1alpha1/providers/%s/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetProviderRequest generates requests for GetProvider
func NewGetProviderRequest(server string, publisher string, name string, version string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "publisher", runtime.ParamLocationPath, publisher)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "name", runtime.ParamLocationPath, name)
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithLocation("simple", false, "version", runtime.ParamLocationPath, version)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1alpha1/providers/%s/%s/%s", pathParam0, pathParam1, pathParam2)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetProviderReadmeRequest generates requests for GetProviderReadme
func NewGetProviderReadmeRequest(server string, publisher string, name string, version string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "publisher", runtime.ParamLocationPath, publisher)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "name", runtime.ParamLocationPath, name)
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithLocation("simple", false, "version", runtime.ParamLocationPath, version)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1alpha1/providers/%s/%s/%s/readme", pathParam0, pathParam1, pathParam2)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUserPublishProviderRequest calls the generic UserPublishProvider builder with application/json body
func NewUserPublishProviderRequest(server string, body UserPublishProviderJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUserPublishProviderRequestWithBody(server, "application/json", bodyReader)
}

// NewUserPublishProviderRequestWithBody generates requests for UserPublishProvider with any type of body
func NewUserPublishProviderRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1alpha1/publish")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewUserCompletePublishProviderRequest calls the generic UserCompletePublishProvider builder with application/json body
func NewUserCompletePublishProviderRequest(server string, body UserCompletePublishProviderJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUserCompletePublishProviderRequestWithBody(server, "application/json", bodyReader)
}

// NewUserCompletePublishProviderRequestWithBody generates requests for UserCompletePublishProvider with any type of body
func NewUserCompletePublishProviderRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1alpha1/publish/complete")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// Healthcheck request
	HealthcheckWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*HealthcheckResponse, error)

	// ListAllProviders request
	ListAllProvidersWithResponse(ctx context.Context, params *ListAllProvidersParams, reqEditors ...RequestEditorFn) (*ListAllProvidersResponse, error)

	// GetProviderVersions request
	GetProviderVersionsWithResponse(ctx context.Context, publisher string, name string, reqEditors ...RequestEditorFn) (*GetProviderVersionsResponse, error)

	// GetProvider request
	GetProviderWithResponse(ctx context.Context, publisher string, name string, version string, reqEditors ...RequestEditorFn) (*GetProviderResponse, error)

	// GetProviderReadme request
	GetProviderReadmeWithResponse(ctx context.Context, publisher string, name string, version string, reqEditors ...RequestEditorFn) (*GetProviderReadmeResponse, error)

	// UserPublishProvider request with any body
	UserPublishProviderWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UserPublishProviderResponse, error)

	UserPublishProviderWithResponse(ctx context.Context, body UserPublishProviderJSONRequestBody, reqEditors ...RequestEditorFn) (*UserPublishProviderResponse, error)

	// UserCompletePublishProvider request with any body
	UserCompletePublishProviderWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UserCompletePublishProviderResponse, error)

	UserCompletePublishProviderWithResponse(ctx context.Context, body UserCompletePublishProviderJSONRequestBody, reqEditors ...RequestEditorFn) (*UserCompletePublishProviderResponse, error)
}

type HealthcheckResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r HealthcheckResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r HealthcheckResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListAllProvidersResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Next      *string          `json:"next"`
		Providers []ProviderDetail `json:"providers"`
	}
	JSON500 *struct {
		Error string `json:"error"`
	}
}

// Status returns HTTPResponse.Status
func (r ListAllProvidersResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListAllProvidersResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetProviderVersionsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]ProviderDetail
	JSON404      *struct {
		Error string `json:"error"`
	}
	JSON500 *struct {
		Error string `json:"error"`
	}
}

// Status returns HTTPResponse.Status
func (r GetProviderVersionsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetProviderVersionsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetProviderResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ProviderDetail
	JSON404      *struct {
		Error string `json:"error"`
	}
	JSON500 *struct {
		Error string `json:"error"`
	}
}

// Status returns HTTPResponse.Status
func (r GetProviderResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetProviderResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetProviderReadmeResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Readme string `json:"readme"`
	}
	JSON404 *struct {
		Error string `json:"error"`
	}
	JSON500 *struct {
		Error string `json:"error"`
	}
}

// Status returns HTTPResponse.Status
func (r GetProviderReadmeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetProviderReadmeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UserPublishProviderResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		// A registered provider version
		Provider ProviderDetail `json:"provider"`
	}
	JSON400 *struct {
		Error string `json:"error"`
	}
	JSON500 *struct {
		Error string `json:"error"`
	}
}

// Status returns HTTPResponse.Status
func (r UserPublishProviderResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UserPublishProviderResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UserCompletePublishProviderResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ProviderDetail
	JSON400      *struct {
		Error string `json:"error"`
	}
	JSON404 *struct {
		Error string `json:"error"`
	}
	JSON500 *struct {
		Error string `json:"error"`
	}
}

// Status returns HTTPResponse.Status
func (r UserCompletePublishProviderResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UserCompletePublishProviderResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// HealthcheckWithResponse request returning *HealthcheckResponse
func (c *ClientWithResponses) HealthcheckWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*HealthcheckResponse, error) {
	rsp, err := c.Healthcheck(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseHealthcheckResponse(rsp)
}

// ListAllProvidersWithResponse request returning *ListAllProvidersResponse
func (c *ClientWithResponses) ListAllProvidersWithResponse(ctx context.Context, params *ListAllProvidersParams, reqEditors ...RequestEditorFn) (*ListAllProvidersResponse, error) {
	rsp, err := c.ListAllProviders(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListAllProvidersResponse(rsp)
}

// GetProviderVersionsWithResponse request returning *GetProviderVersionsResponse
func (c *ClientWithResponses) GetProviderVersionsWithResponse(ctx context.Context, publisher string, name string, reqEditors ...RequestEditorFn) (*GetProviderVersionsResponse, error) {
	rsp, err := c.GetProviderVersions(ctx, publisher, name, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetProviderVersionsResponse(rsp)
}

// GetProviderWithResponse request returning *GetProviderResponse
func (c *ClientWithResponses) GetProviderWithResponse(ctx context.Context, publisher string, name string, version string, reqEditors ...RequestEditorFn) (*GetProviderResponse, error) {
	rsp, err := c.GetProvider(ctx, publisher, name, version, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetProviderResponse(rsp)
}

// GetProviderReadmeWithResponse request returning *GetProviderReadmeResponse
func (c *ClientWithResponses) GetProviderReadmeWithResponse(ctx context.Context, publisher string, name string, version string, reqEditors ...RequestEditorFn) (*GetProviderReadmeResponse, error) {
	rsp, err := c.GetProviderReadme(ctx, publisher, name, version, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetProviderReadmeResponse(rsp)
}

// UserPublishProviderWithBodyWithResponse request with arbitrary body returning *UserPublishProviderResponse
func (c *ClientWithResponses) UserPublishProviderWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UserPublishProviderResponse, error) {
	rsp, err := c.UserPublishProviderWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUserPublishProviderResponse(rsp)
}

func (c *ClientWithResponses) UserPublishProviderWithResponse(ctx context.Context, body UserPublishProviderJSONRequestBody, reqEditors ...RequestEditorFn) (*UserPublishProviderResponse, error) {
	rsp, err := c.UserPublishProvider(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUserPublishProviderResponse(rsp)
}

// UserCompletePublishProviderWithBodyWithResponse request with arbitrary body returning *UserCompletePublishProviderResponse
func (c *ClientWithResponses) UserCompletePublishProviderWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UserCompletePublishProviderResponse, error) {
	rsp, err := c.UserCompletePublishProviderWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUserCompletePublishProviderResponse(rsp)
}

func (c *ClientWithResponses) UserCompletePublishProviderWithResponse(ctx context.Context, body UserCompletePublishProviderJSONRequestBody, reqEditors ...RequestEditorFn) (*UserCompletePublishProviderResponse, error) {
	rsp, err := c.UserCompletePublishProvider(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUserCompletePublishProviderResponse(rsp)
}

// ParseHealthcheckResponse parses an HTTP response from a HealthcheckWithResponse call
func ParseHealthcheckResponse(rsp *http.Response) (*HealthcheckResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &HealthcheckResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseListAllProvidersResponse parses an HTTP response from a ListAllProvidersWithResponse call
func ParseListAllProvidersResponse(rsp *http.Response) (*ListAllProvidersResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListAllProvidersResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Next      *string          `json:"next"`
			Providers []ProviderDetail `json:"providers"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			Error string `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetProviderVersionsResponse parses an HTTP response from a GetProviderVersionsWithResponse call
func ParseGetProviderVersionsResponse(rsp *http.Response) (*GetProviderVersionsResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetProviderVersionsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []ProviderDetail
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest struct {
			Error string `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			Error string `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetProviderResponse parses an HTTP response from a GetProviderWithResponse call
func ParseGetProviderResponse(rsp *http.Response) (*GetProviderResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetProviderResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ProviderDetail
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest struct {
			Error string `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			Error string `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetProviderReadmeResponse parses an HTTP response from a GetProviderReadmeWithResponse call
func ParseGetProviderReadmeResponse(rsp *http.Response) (*GetProviderReadmeResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetProviderReadmeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Readme string `json:"readme"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest struct {
			Error string `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			Error string `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseUserPublishProviderResponse parses an HTTP response from a UserPublishProviderWithResponse call
func ParseUserPublishProviderResponse(rsp *http.Response) (*UserPublishProviderResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UserPublishProviderResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// A registered provider version
			Provider ProviderDetail `json:"provider"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			Error string `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			Error string `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseUserCompletePublishProviderResponse parses an HTTP response from a UserCompletePublishProviderWithResponse call
func ParseUserCompletePublishProviderResponse(rsp *http.Response) (*UserCompletePublishProviderResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UserCompletePublishProviderResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ProviderDetail
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			Error string `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest struct {
			Error string `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			Error string `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Healthcheck
	// (GET /v1alpha1/health)
	Healthcheck(w http.ResponseWriter, r *http.Request)
	// List Providers
	// (GET /v1alpha1/providers)
	ListAllProviders(w http.ResponseWriter, r *http.Request, params ListAllProvidersParams)
	// Get Provider Versions
	// (GET /v1alpha1/providers/{publisher}/{name})
	GetProviderVersions(w http.ResponseWriter, r *http.Request, publisher string, name string)
	// Get Provider
	// (GET /v1alpha1/providers/{publisher}/{name}/{version})
	GetProvider(w http.ResponseWriter, r *http.Request, publisher string, name string, version string)
	// Get Provider Readme
	// (GET /v1alpha1/providers/{publisher}/{name}/{version}/readme)
	GetProviderReadme(w http.ResponseWriter, r *http.Request, publisher string, name string, version string)
	// Publish a Provider
	// (POST /v1alpha1/publish)
	UserPublishProvider(w http.ResponseWriter, r *http.Request)
	// Complete Publishing a Provider
	// (POST /v1alpha1/publish/complete)
	UserCompletePublishProvider(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.HandlerFunc) http.HandlerFunc

// Healthcheck operation middleware
func (siw *ServerInterfaceWrapper) Healthcheck(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Healthcheck(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// ListAllProviders operation middleware
func (siw *ServerInterfaceWrapper) ListAllProviders(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAllProvidersParams

	// ------------- Optional query parameter "withDev" -------------
	if paramValue := r.URL.Query().Get("withDev"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "withDev", r.URL.Query(), &params.WithDev)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "withDev", Err: err})
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAllProviders(w, r, params)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// GetProviderVersions operation middleware
func (siw *ServerInterfaceWrapper) GetProviderVersions(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "publisher" -------------
	var publisher string

	err = runtime.BindStyledParameter("simple", false, "publisher", chi.URLParam(r, "publisher"), &publisher)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "publisher", Err: err})
		return
	}

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameter("simple", false, "name", chi.URLParam(r, "name"), &name)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProviderVersions(w, r, publisher, name)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// GetProvider operation middleware
func (siw *ServerInterfaceWrapper) GetProvider(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "publisher" -------------
	var publisher string

	err = runtime.BindStyledParameter("simple", false, "publisher", chi.URLParam(r, "publisher"), &publisher)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "publisher", Err: err})
		return
	}

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameter("simple", false, "name", chi.URLParam(r, "name"), &name)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	// ------------- Path parameter "version" -------------
	var version string

	err = runtime.BindStyledParameter("simple", false, "version", chi.URLParam(r, "version"), &version)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "version", Err: err})
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProvider(w, r, publisher, name, version)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// GetProviderReadme operation middleware
func (siw *ServerInterfaceWrapper) GetProviderReadme(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "publisher" -------------
	var publisher string

	err = runtime.BindStyledParameter("simple", false, "publisher", chi.URLParam(r, "publisher"), &publisher)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "publisher", Err: err})
		return
	}

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameter("simple", false, "name", chi.URLParam(r, "name"), &name)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	// ------------- Path parameter "version" -------------
	var version string

	err = runtime.BindStyledParameter("simple", false, "version", chi.URLParam(r, "version"), &version)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "version", Err: err})
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProviderReadme(w, r, publisher, name, version)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// UserPublishProvider operation middleware
func (siw *ServerInterfaceWrapper) UserPublishProvider(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UserPublishProvider(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// UserCompletePublishProvider operation middleware
func (siw *ServerInterfaceWrapper) UserCompletePublishProvider(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UserCompletePublishProvider(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1alpha1/health", wrapper.Healthcheck)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1alpha1/providers", wrapper.ListAllProviders)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1alpha1/providers/{publisher}/{name}", wrapper.GetProviderVersions)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1alpha1/providers/{publisher}/{name}/{version}", wrapper.GetProvider)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1alpha1/providers/{publisher}/{name}/{version}/readme", wrapper.GetProviderReadme)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1alpha1/publish", wrapper.UserPublishProvider)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1alpha1/publish/complete", wrapper.UserCompletePublishProvider)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xaWXPbvhH/Khg0j4wkJ/mntd7cnG5c22M77XQSP0DEUkICAgwAytZ49N07OEiChyzG",
	"9n+SzjQvsUhgscdvD+zyDqcyL6QAYTSe32EFP0rQ5u+SMnAPzssFZ3p1ruSaUVAX/r19k0phQLg/SVFw",
	"lhLDpJh+01LYZzpdQU7sX4WSBSgTCFJY2//MpgA8xwspORCBtwkWJIfojTaKiaV9UXgWQA2+VZLDe8Yr",
	"4jpVrLCM4DkmAhGlyAbJDGWMgz1Bo0wqZDchA3nBiQGNjEQLQGXBJaFAcYKZgVwPHhceOLr29xqUZl7i",
	"zlrLG/womQKK518iKYKozd5YiOv6CLn4BqnBW/vPktKFFNqL+U4pqS7Ck0fYAiyd/az7ZUOcJR2NHwnk",
	"FiMFplQCKMqUzJFZATo6P55YhX0Ews3qCZhfOUKbITB1+K9WjpHAs5euIP2OKp2jhaQbx/wJ06ZyBf0E",
	"Mgi4dXtEyTlZcMBzo0pIBnygOtSurtH5TEGG5/gv08aJp/4oPa3YfAuGMN6Hbhee9QGJ52qMst7dkrzg",
	"UCvKntJECkJzeAIdKUdoP0rDujF8Vzwiz6RjuxvnHs13ymVJM6lyt/wqBJvPLsh8VnwwunCSLyj5SATl",
	"oO5f6sXds0Zy6Bx8cTIQKKvgiJh2vvodNogIitaEl/VDHx7R54sT3FVxgm+fL+Xz8DAnxRfPw/UOU+0Q",
	"M9mrs77YO4Ucg4PKysiamLBDoVGhQLOljVyWiksWXnAmlqhyEkS0BqMn6EykEH6gFVkDWgCIOpEkyPol",
	"BwMoRP8WEb2SJac286SEc6ATp6fgv9ZIb6TI2HIohUZCdG15ZU2lyRIc79ZwqSOD1kQxG2Mm1nzM2GCD",
	"30ZbB6KOhlSB8WdkpOQGzzPCNTQELv2KZCCf+yd3GESZW6MHstfN5iu7Itnj1u5ttCkopWfdJAizaMWc",
	"jkvWCu1tpowshdSGpeND7Nt6z4kcLA7uSVFNSB8byHENjn07Lv2qXSHe+lmlxIrDtgLqg667UIm0OxQE",
	"tJEFZ8uVwwyjVhcmy4h4sbidHR4qx1Jbaz0bcVgD3yfhiVyeuHXbBOd6uT85eKp+cSxUi5dxEt3++KNc",
	"6duC5fzA59ET6+2q74pHzrGtz6GsFKl9iphwPlkHgZsVS1coJeKrcOFVgZalSkFPvoqv4ohSZrcRjjIG",
	"nPqA5KKLCn5dKhcrUU42NpQQSoF+FUwggrLSlAqQLiBlWUhb1vvbCg+6uGvc0v2/1y/dqkiXQQsDjllb",
	"K4oGx6fvz3CC311cnF3gBP/76OL0+PRDm17Y1eVk2CzqMIVbI7/Rl+b1Xx23/wQzkJYzRXK4ker7cOis",
	"S4O39my7EX1iBtW7UCjag+Gqqp46q3p4xgH2fX3akD6rVY7TAcWdRyGiCy0FS6YNKKANmJoLRafMfNjV",
	"6inuNpFBz5v4M8bPFq/o4cHBATnIshev3ZGdkvaRSkmzusC4fHmkxKAKUgXEAD0y95RrRzb/7yaRBxiO",
	"ifEWCMcik4+4D/9cikhwWdB7JHya621PT0lf+zXnsdJj9gaQFIAwMhPRwwW8fE0XMDts46nWeg9R9g0l",
	"hvhrbAWpiZE5dx0FF45JEzR6IKNMF5xsTnfZkqVyGDU+CwzrvauGmv9xijhYLP62eP1q9hKAvmgpQg/c",
	"UCvOw5mn3rZ7QFkxGIHiXmiF9f+qEfOnxpttYit/n2YHChCXx9yfpE6/560l95cmJBRr7cSox9+aIhKb",
	"YqixZXONe4Vk1lQMuF1Z9w/sFUUtxnSsu4uYaFd5l3WI6edPr4bgF29knkuB3hPTJNZ+AfLMonLABZ41",
	"oawfl+tK/iE2CneI7d5bxU4TNRTGhHeX3x9Y8qsYqfdtakxm5SJqCebBIL5y22MFXQWCozVUkehgLvel",
	"jrV5Y+EIeJdVEuihLhDs+Wv718OlfW8LbNzrEVhfI6kpCUfNSdbvnBO6nXHBF536k6qqz68uzm0+mEh5",
	"SYE617JCEMMWjDOzQTfMrNA/Ls9Okdceeo4I54E5jYgClJZKgTB8gzwz2vJc1eKBvwfdzFvOfN3Fy247",
	"emn3tTZG9ikqH+lr7Tirrj9AE1TFzcp81T73w12woqZMIYvSlie+hx3buPK0IVbG3qb+tP5IrN7BFhgL",
	"lY7reaWmSfI4Cte28lIcz/HKmELPp1NSsImvrtVmkrqFGTEwYbLvMjYPDIV+dBEI+GFAHH3vWRwl9zk+",
	"mMzsebIAQQqG5/jlZDaZWRQSs3IImq4PCC9W5GDqexv22bJqYrWbf6ZUQiOCPl5dnaMXsxk6+9T0/FkF",
	"kcCyBrVmqeuGhqaJlcBi192rj2l7eIA7I5sXs1mfhbNPvuVX5jlRmw4B+6YRpjUACPK0Dz9h2hxxfh41",
	"8gtir5/G7frSPdxGjbewRhknS3TDOA9DGxc76uOQjztMLBGFNYrHBMxS+VGCM1GAUCCK43tIbzpzPayb",
	"oRBdr5sOj162Cf5jzO72xKytdEsZxWozZGkV5svXFF/vsMT0rq5Dt9M7q4DtTrAVRFtVIoKWIECxtOkc",
	"TF3nPZX5ggnfyiGCoiUYH5VKzhG3HMosskoPeh+g1k6oovUOCI4eZzzNmKkXHSzoE/xq9uqnrfYEtv4A",
	"jalRpKieyXvOw7wZzaoBe3wNaUKyn+DtrF23ySCtcI0ZT+Z6NCindyF+bnfGjgg9j0XNz4DlNwbH74CJ",
	"6PuA/wV0TZtJ7b0J16dVuzSMqJhG0WxiJzLDsPYhyWPHUPo3iUO1YP9HXI04L5S7IEg9AKbQWkIECbip",
	"VZmgjSzdKCR1NyALraPzY5SX3LCCAzKs+gTI9ett5u02ilEpDOOOkBvp5kR9D/39aIpLdD3cdZMaPwn2",
	"TcEV0X4QrMs0Ba1tDt9EU2FmUEqEkMZeM+Qa1I1ixoCYfBX/kaWvxQTYM2V1pL/jeWErPkWZL3w/pe0y",
	"nzWozucMwRL+y67NbuhGH39Nd3z5tX1kfuhd3n+qI1Jnjh2jzTFT/yrHzH6F4ze4Hcg0V0DyXrnpN0wr",
	"tO12iTcDHxt4xOz85ADdrOrvFexyFqF6EFfVGXvx9aT1Ah74Bu7X1CUPwcwvSjE1HM5jONyDOvfBh1pX",
	"qaa5/8+nUy5TwldSm/nhbHaA7RUubK+7ByFp2XwQnjjC2+vtfwMAAP//KJ8GsGUqAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
