name: Generate Go SDK

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "The provider-registry repository tag to release"
        type: string
        required: true

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    steps:
      - name: Print params
        run: echo "Generating docs for common-fate tag ${PROVIDER_REGISTRY_TAG}"
        env:
          PROVIDER_REGISTRY_TAG: ${{ github.event.inputs.tag }}

      - name: Check version tag format
        run: |
          (echo "$PROVIDER_REGISTRY_TAG" | grep -Eq  ^v[0-9]+.[0-9]+.[0-9]+$) && echo "version tag matches vMAJOR.MINOR.PATCH format" || (echo "${PROVIDER_REGISTRY_TAG} did not match vMAJOR.MINOR.PATCH format (did you forget the 'v'?)" && exit 1)
        env:
          PROVIDER_REGISTRY_TAG: ${{ github.event.inputs.tag }}

      - uses: actions/setup-go@v2
        with:
          go-version: "1.19.0"

      - name: Checkout SDK
        uses: actions/checkout@v3

      - name: Check out Profile Registry repository
        uses: actions/checkout@v2
        with:
          repository: common-fate/profile-registry
          fetch-depth: 0
          ref: ${{ github.event.inputs.tag }}
          path: profile-registry

      - name: Generate SDK
        run: go generate

      - name: Open PR
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update Provider Registry
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: "build-provider-registry-sdk-${{ github.event.inputs.tag }}"
          delete-branch: true
          title: "[New Release] Generate Provider Registry for (${{ github.event.inputs.tag }})"
          body: |
            Generated Provider Registry Setup docs for common-fate ${{ github.event.inputs.tag }}
          labels: |
            automated pr
